app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path("users/", views.user_list, name="user_list"),
    path("users/<int:id>", views.user_details, name="user_details"),
]

usersdemo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
    path("", lambda request: redirect("app:user_list")),
]

app/models.py
from django.db import models
from django.core.validators import MinLengthValidator


# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=300, validators=[MinLengthValidator(2)])
    email = models.EmailField(unique=True)
    age = models.PositiveIntegerField(blank=True)
    ssn = models.CharField(unique=True)

app/views.py
from django.shortcuts import render, get_object_or_404
from .models import User


# Create your views here.
def user_list(request):
    users = User.objects.all()
    return render(request, "users/user_list.html", {"users": users})


def user_details(request, id):
    user = get_object_or_404(User, id=id)
    return render(request, "users/user_details.html", {"user": user})

app/templates/users/user_details.html
<!DOCTYPE html>
<html>

<head>
  <title>User {{ user.name }}</title>
</head>

<body>
  <h1>{{ user.name }} ({{ user.ssn }})</h1>

  <ul>
    <li>Age: {{ user.age }}</li>
    <li>Email: {{ user.email }}</li>
  </ul>

  <a href="{% url 'app:user_list' %}">Back to index</a>
</body>

</html>

app/templates/users/user_list.html
<!DOCTYPE html>
<html>

<head>
  <title>Users List</title>

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <div style="display: flex; align-items: center;">
    <h1>Users</h1>
    <img src="{% static 'images/users.jpeg' %}" alt="Generic users" style="height: 50px; margin-left: 10px;">
  </div>


  <ul>
    {% for user in users %}
    <li><a href="{% url 'app:user_details' id=user.id %}">{{ user.name }}</a> ({{ user.ssn }})</li>
    {% endfor %}
  </ul>
</body>

</html>